train:
    # [Input files to build vocabulary]
    input: tokenizer/data/train.txt
    # [Output file to save vocabulary]
    model_prefix: tokenizer/output/tokenizer/m

    vocab_size: 32000
    user_defined_symbols:
        - "[CLS]"
        - "[SEP]"
